=== mattramey/Save-Exotic-Animals-Trust/seatrust.dtd
<!--
   New Perspectives on XML
   Tutorial 2
   Case Problem 3

   The Save Exotic Animals Trust DTD
   Author: Matt Ramey
   Date:  5/30/24

   Filename:          seatrust.dtd
   Supporting file:   roster.xml
-->
<!ELEMENT roster (donor+)>
<!ELEMENT donor (name, address, phone+, email?, donation, method, effectiveDate)>
<!ATTLIST donor level (founder | sponsor | patron | friendship) #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (home | cell | work) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT donation (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT effectiveDate (#PCDATA)>

=== mattramey/Save-Exotic-Animals-Trust/roster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
   New Perspectives on XML
   Tutorial 2
   Case Problem 3

   The Save Exotic Animals Trust donor roster
   Author: Matt Ramey
   Date: 5/30/24

   Filename:             roster.xml
   Supporting document:  seatrust.dtd
-->
<!DOCTYPE roster SYSTEM "seatrust.dtd">
<roster>

   <!--Founding
   Circle Donors
   ===================-->

   <donor level="founder">
      <name>David Brennan</name>
      <address>5133 Oak Street Windermere, FL 34786</address>
      <phone type="home">(407) 555-8981</phone>
      <phone type="cell">(407) 555-8189</phone>
      <email>dbrennan@example.net</email>
      <donation>$50,000</donation>
      <method>phone</method>
      <effectiveDate>9/1/1982</effectiveDate>
   </donor>


   <donor level="founder">
      <name>Cindy Wu</name>
      <address>31 Alice Avenue Windermere, FL 34786</address>
      <phone type="home">(407) 555-7212</phone>
      <email>cwu@example.net</email>
      <donation>$50,000</donation>
      <method>phone</method>
      <effectiveDate>9/1/1982</effectiveDate>
   </donor>

   <!--Sponsorship
   Donors
================
 -->

   <donor level="sponsor">
      <name>David Olson</name>
      <address>5133 Oak Street Windermere, FL 34786</address>
      <phone type="home">(407) 555-8981 </phone>
      <phone type="home">(407) 555-8189 </phone>
      <email>dolson@example.net</email>
      <donation>$25,000</donation>
      <method>personal</method>
      <effectiveDate>7/3/1985</effectiveDate>
   </donor>

   <donor level="sponsor">
      <name>Wilmer Stonehedge</name>
      <address>31 Alice Avenue Windermere, FL 34786</address>
      <phone type="cell">(407) 555-7212</phone>
      <email>wstone@example.net</email>
      <donation>$25,000</donation>
      <method>personal</method>
      <effectiveDate>10/3/1994</effectiveDate>
   </donor>

   <!--Patron
   Donors
============
-->

   <donor level="patron">
      <name>Lee Unwin</name>
      <address>451 Unwin Ct. Orlando, FL 32801</address>
      <phone type="cell">(407) 555-9082</phone>
      <email>leeunwin@example.net</email>
      <donation>$18,000</donation>
      <method>personal</method>
      <effectiveDate>11/1/1998</effectiveDate>
   </donor>

   <donor level="patron">
      <name>Jane Whitney</name>
      <address>87 Hilltop Drive Windermere, FL 34786</address>
      <phone type="work">(407) 555-7493</phone>
      <donation>$15,000</donation>
      <method>personal</method>
      <effectiveDate>11/1/1998</effectiveDate>
   </donor>

   <donor level="patron">
      <name>Andrew Sanchez</name>
      <address>891 Lindon Lane Windermere, FL 34786</address>
      <phone type="cell">(407) 555-4313</phone>
      <email>asanchez@example.com</email>
      <donation>$15,000</donation>
      <method>personal</method>
      <effectiveDate>3/4/2000</effectiveDate>
   </donor>

   <!--Friendship
   Donor
===============
-->

   <donor level="friendship">
      <name>Gary Windt</name>
      <address>55 Hawking Street, Windermere, FL 34786</address>
      <phone type="home">(407) 555-9939</phone>
      <email>windtg@example.com</email>
      <donation>$1000</donation>
      <method>phone</method>
      <effectiveDate>2000/03/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Cynthia Browne</name>
      <address>71 Circuit Ct., Wheaton, KY 89321</address>
      <phone type="cell">(407) 555-3813</phone>
      <email>cynthia@example.com</email>
      <donation>$1000</donation>
      <method>phone</method>
      <effectiveDate>2000/03/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Howard Li</name>
      <address>4312 East Oak Avenue, Youngston, KY 89318</address>
      <phone type="home">(407) 555-3921</phone>
      <donation>$1000</donation>
      <method>mail</method>
      <effectiveDate>2011/03/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Uma Thu</name>
      <address>25 Longton Lane, Windermere, FL 34786</address>
      <phone type="cell">(407) 555-8730</phone>
      <donation>$1000</donation>
      <method>personal</method>
      <effectiveDate>2012/04/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Alan Wilkes</name>
      <address>321 Ashburn, Jasper, KY 89831</address>
      <phone type="home">(407) 555-1181</phone>
      <email>wilkes_alan@example.edu</email>
      <donation>$500</donation>
      <method>mail</method>
      <effectiveDate>2012/01/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Steve Bones</name>
      <address>900 Lawton Street, Wheaton, KY 89211</address>
      <phone type="cell">(407) 555-5434</phone>
      <donation>$500</donation>
      <method>personal</method>
      <effectiveDate>2012/09/14</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Jeri White</name>
      <address>Hawkes Lane, Windermere, FL 89211</address>
      <phone type="cell">(407) 555-8828</phone>
      <email>jeri_white@example.com</email>
      <donation>$300</donation>
      <method>phone</method>
      <effectiveDate>2012/12/04</effectiveDate>
   </donor>
   <donor level="friendship">
      <name>Tom Thomas</name>
      <address>Rigel Avenue, Apopka, FL 32703</address>
      <phone type="home">(407) 555-8311</phone>
      <donation>$100</donation>
      <method>phone</method>
      <effectiveDate>2012/02/04</effectiveDate>
   </donor>

</roster>
